MIDlet-Vendor:midlet@wintermute.de
MIDlet-Version:1.0
MIDlet-Info-URL:http://wintermute.de/kakuro
Ant-Version:Apache Ant 1.7.0
Manifest-Version:1.0
Created-By:1.6.0_02-b06 (Sun Microsystems Inc.)
MicroEdition-Configuration:CLDC-1.0
MIDlet-Name:k4kur0
MIDlet-1:k4kur0,/kakuro.png,de.wintermute.kakuro.midlet.KakuroMidlet
MIDlet-Description:A Kakuro game.
MicroEdition-Profile:MIDP-1.0
